# Generated by Django 5.1.4 on 2025-01-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_rename_reason_leave_actions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shift",
            name="actions",
        ),
        migrations.AlterField(
            model_name="leave",
            name="actions",
            field=models.CharField(max_length=255),
        ),
    ]
